"""empty message

Revision ID: d461478cfc45
Revises: 
Create Date: 2024-07-09 14:32:33.922820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd461478cfc45'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storage', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('storage', sa.Column('capacity', sa.Integer(), nullable=False))
    op.add_column('storage', sa.Column('current_stock', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('storage', 'current_stock')
    op.drop_column('storage', 'capacity')
    op.drop_column('storage', 'description')
    # ### end Alembic commands ###
