"""initial

Revision ID: c038dda0915f
Revises:
Create Date: 2024-07-22 11:00:37.797996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'jopa2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('permissions', sa.JSON(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('username', sa.String(), nullable=False),
                    sa.Column('registered_at', sa.TIMESTAMP(), nullable=True),
                    sa.Column('role_id', sa.Integer(), nullable=True),
                    sa.Column('hashed_password', sa.String(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('is_superuser', sa.Boolean(), nullable=False),
                    sa.Column('is_verified', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('products',
                    sa.Column('id', sa.Integer, primary_key=True),
                    sa.Column('category', sa.String(length=255), nullable=False),
                    sa.Column('quantity', sa.Integer, nullable=False),
                    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False)
                    )
    op.create_table('purchases',
                    sa.Column('id', sa.Integer, primary_key=True),
                    sa.Column('cust_id', sa.String(length=255), nullable=False),
                    sa.Column('time', sa.TIMESTAMP(), nullable=False),
                    sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=False),
                    sa.Column('pr_list', sa.PickleType(), nullable=True)
                    )
    op.create_table('baskets',
                    sa.Column('id', sa.Integer, primary_key=True),
                    sa.Column('pr_category', sa.String(length=255), nullable=False),
                    sa.Column('cust_id', sa.Integer, nullable=False),
                    sa.Column('pr_price', sa.Numeric(precision=10, scale=2), nullable=False),
                    sa.Column('quantity', sa.Integer, nullable=False)
                    )
    op.drop_table('product_db')
    op.drop_table('customers')
    op.drop_table('mytable')
    op.drop_table('purchases')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchases',
                    sa.Column('purch_id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('cust_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('purch_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
                    sa.Column('total_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
                    sa.Column('pr_list', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('purch_id', name='purchases_pkey')
                    )
    op.create_table('mytable',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
                    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='mytable_pkey')
                    )
    op.create_table('customers',
                    sa.Column('customer_id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('first_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
                    sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
                    sa.Column('phone_number', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('customer_id', name='customers_pkey')
                    )
    op.create_table('product_db',
                    sa.Column('product_id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('pr_category_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('product_id', name='product_db_pkey')
                    )
    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('products')
    op.drop_table('baskets')
    # ### end Alembic commands ###
